package com.sample
 
import com.healthriskassessment.dto.UserDataDTO;
import com.healthriskassessment.dto.HealthDataDTO;
import com.healthriskassessment.model.enums.BMICategory;


rule "Calculate BMI"
	when 
		$userData: UserDataDTO($weight: weight, $height: height)
	    $healthData: HealthDataDTO()
	then
		System.out.println("Calculate BMI fired " + ($weight/($height*$height+0.0f))*10000);
		modify($healthData) {setBmiValue(($weight/($height*$height+0.0f))*10000);};
		System.out.println($healthData.getBmiValue());
end


rule "BMI category severe thinness"
	when
		$healthData: HealthDataDTO(bmiValue < 16, bmiValue != 0)
	then
		System.out.println("BMI category severe thinness fired");
		modify($healthData) {setBmiCategory(BMICategory.SEVERE_THINNESS);};
end


rule "BMI category moderate thinness"
	when
		$healthData: HealthDataDTO(bmiValue >= 16, bmiValue < 17  )
	then
		System.out.println("BMI category moderate thinness fired");
		modify($healthData) {setBmiCategory(BMICategory.MODERATE_THINNESS);};
end


rule "BMI category mild thinness"
	when
		$healthData: HealthDataDTO(17 <= bmiValue, bmiValue < 18.5 )
	then
		System.out.println("BMI category mild thinness fired");
		modify($healthData) {setBmiCategory(BMICategory.MILD_THINNESS);};
end


rule "BMI category normal"
	when
		$healthData: HealthDataDTO(18.5 <= bmiValue, bmiValue < 25 )
	then
		System.out.println("BMI category normal fired");
		modify($healthData) {setBmiCategory(BMICategory.NORMAL);};
end


rule "BMI category overweight"
	when
		$healthData: HealthDataDTO(25 <= bmiValue, bmiValue < 30 )
	then
		System.out.println("BMI category overweight fired");
		modify($healthData) {setBmiCategory(BMICategory.OVERWEIGHT);};		
end


rule "BMI category obese class I"
	when
		$healthData: HealthDataDTO(30 <= bmiValue, bmiValue < 35 )
	then
		System.out.println("BMI category obese class I fired");
		modify($healthData) {setBmiCategory(BMICategory.OBESE_CLASS_I);};		
end


rule "BMI category obese class II"
	when
		$healthData: HealthDataDTO(35 <= bmiValue, bmiValue < 40 )
	then
		System.out.println("BMI category obese class II fired");
		modify($healthData) {setBmiCategory(BMICategory.OBESE_CLASS_II);};		
end


rule "BMI category obese class III"
	when
		$healthData: HealthDataDTO(bmiValue > 40 )
	then
		System.out.println("BMI category obese class III fired");
		modify($healthData) {setBmiCategory(BMICategory.OBESE_CLASS_III);};
end
 